// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC5Wgu2FSAY_JOmWDiu7U5F0DxLbnbZP8',
    appId: '1:233738305831:android:236b5839c6a0673b666902',
    messagingSenderId: '233738305831',
    projectId: 'greenvolt-480dd',
    storageBucket: 'greenvolt-480dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHmIPEbOa3BkKz568QUvMKebekqwn2iZA',
    appId: '1:233738305831:ios:69b9f8b7666a02f3666902',
    messagingSenderId: '233738305831',
    projectId: 'greenvolt-480dd',
    storageBucket: 'greenvolt-480dd.firebasestorage.app',
    iosBundleId: 'com.example.greenvolt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8wMDPDc1o-A11M7nW_dx50m0MowSnxQ4',
    appId: '1:233738305831:web:8407a8e46aca0e9e666902',
    messagingSenderId: '233738305831',
    projectId: 'greenvolt-480dd',
    authDomain: 'greenvolt-480dd.firebaseapp.com',
    storageBucket: 'greenvolt-480dd.firebasestorage.app',
  );

}